### ISSUE TITLE
Enhancement: Support Powershell Syntax for Maven Args

### ISSUE THREAD

**Issue by aanutter** [kirksl/karate-runner#10]
As powershell is the default shell for VSCode since Windows 10, would be nice to have it supported by the runner.  Powershell requires single quotes around all `-D` Maven args, which means double quotes are then required for string values of the arg.

**Comment by kirksl** [comment]
@aanutter this has been sitting for awhile and not seeing many requests for this.  nevertheless i'd like to tackle this in the future when we remove some of the entanglement such as getting this to work with debug configurations where many things are statically set today.

seems easy enough once we get this outside complexity out of the way.
https://stackoverflow.com/questions/6347985/cannot-run-maven-using-mvn-d-argument-within-microsoft-powershell-but-works

**Comment by hahampis** [comment]
Hello, just a tip: I am on VSCode version 1.52.1 and there is now a setting called `Automation shell: Windows` which is different from the already existing `Shell: Windows` setting (I don't know when this setting was first introduced). I have set the Automation shell to `cmd` for the Karate runner extension to run properly and the generic shell to `powershell`  for new terminals I open for myself. So now I have the best of both worlds! My settings.json looks like this:

   "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.automationShell.windows": "C:\\Windows\\System32\\cmd.exe"

**Comment by kirksl** [comment]
@hahampis nice.  thanks for helping to solve this.  i'm going to re-open this and add this as one of our options.  we plan to fix this in our next release in our next release to support the upcoming karate 1.0.0 release.

**Comment by kirksl** [comment]
@aanutter we released 0.9.6 today which disregards the user's personal console selection(eg cmd, powershell) on windows.  internally the extension runs everything with cmd.exe.  happy to hear your feedback and if you still think powershell specific support is needed.  https://github.com/kirksl/karate-runner/commit/0e365d886a90ea50cd53f3be46cc484de5f92203

**Comment by kirksl** [comment]
closing due to no response, additionally we've resolved issues related to users with powershell as their default.  the extension disregards user defaults and always runs with cmd.exe.
