### ISSUE TITLE
Codelens fails to load when installing extension https://marketplace.visualstudio.com/items?itemName=pxius.karatesyntax

### ISSUE THREAD

**Issue by techshashank80** [kirksl/karate-runner#117]
Hi
I have created the maven-java project. I installed the karate runner and followed the steps mentioned here https://github.com/intuit/karate/wiki/Karate-Robot-Windows-Install-Guide
But I am not seeing the run /debug option in the feature file however I was able to see it in 1.41.1 
After upgrading to the latest 1.60.0, I cant see
I used a sample maven-Gradle project but still the same issue.
attaching the screenshot of the sample project:

![image](https://user-images.githubusercontent.com/34492336/133707095-aeb56b97-905a-4710-8e46-c6c66bacafb2.png)

![image](https://user-images.githubusercontent.com/34492336/133707157-75cf0ed8-b91a-4953-ba6c-ca9a3fbb32ee.png)

Please let me know if you need more information.

Here is my config
Win10
JDK 1.8.302
karate 1.1.0

**Comment by kirksl** [comment]
@techshashank80 can you uninstall Karate IDE and possibly other Karate extensions like the extension pack.  I know Karate IDE for example was a project copied from Karate Runner and very likely creating a conflict.  You may need to delete the extension files in your computer profile too for example under /yourusername/.vscode/extensions

**Comment by techshashank80** [comment]
Thank you @kirksl, as you suggested I uninstalled the Karate IDE, deleted it from the .vscode profile. Still, I was not able to see Debug/Run then I uninstalled another extension 'Karate Extension Pack' then it worked fine. Now I can see it.

**Comment by kirksl** [comment]
@techshashank80 happy to help.  i'm going to keep this ticket open to see if i can update Karate Runner to defend against this conflict.  unfortunately many times these things are out of our control.

**Comment by kirksl** [comment]
marked external.  we could not find a resolution to defend against this in our project.
issue opened in the project affecting this project https://github.com/pXius/karatesyntax/issues/1
