### ISSUE TITLE
Karate runner not able to read the file using karate.read()

### ISSUE THREAD

**Issue by techshashank80** [kirksl/karate-runner#120]
I have the script is running fine with IntelliJ and Maven command. But it's not running with karate runner using "karate Run" from the feature file.

Karate. Read not working with Karate runner ext,. any clue?
Karate runner is not recognizing the karate.read('classpath:xxx)

**Comment by kirksl** [comment]
@techshashank80 greatly appreciate it if you can copy and paste the error you are seeing in your VSCode terminal.  another thing that would really help solve this quickly is if you can send me a zip file of a project that can reproduce the problem.

**Comment by techshashank80** [comment]
Thanks for the response @kirksl here is error log 
I used the sample karate runner project for this just added one json file and trying to read it. 

`ir to: target\karate-reports_1632264537290
15:48:57.315 [main]  INFO  c.intuit.karate.core.FeatureRuntime - found scenario at line: 8
15:48:58.176 [main]  ERROR com.intuit.karate - src/test/java/org/company/order.feature:9
* def locaters = read('classpath:org/company/page_objects/readData.json')
js failed:
[>>>>](url)
01: read('classpath:org/company/page_objects/readData.json')
<<<<
org.graalvm.polyglot.PolyglotException: not found: org/company/page_objects/readData.json       
- com.intuit.karate.resource.ResourceUtils.getResource(ResourceUtils.java:120)
- com.intuit.karate.core.ScenarioFileReader.toResource(ScenarioFileReader.java:122)
- com.intuit.karate.core.ScenarioFileReader.readFileAsStream(ScenarioFileReader.java:99)        
- com.intuit.karate.core.ScenarioFileReader.readFileAsString(ScenarioFileReader.java:95)        
- com.intuit.karate.core.ScenarioFileReader.readFile(ScenarioFileReader.java:53)
- com.intuit.karate.core.ScenarioEngine.lambda$new$0(ScenarioEngine.java:124)
- <js>.:program(Unnamed:1)

src/test/java/org/company/order.feature:9
---------------------------------------------------------
feature: src/test/java/org/company/order.feature:8
scenarios:  1 | passed:  0 | failed:  1 | time: 0.1504
---------------------------------------------------------

15:48:58.806 [main]  INFO  com.intuit.karate.Suite - <<fail>> feature 1 of 1 (0 remaining) src/test/java/org/company/order.feature
Karate version: 1.1.0
======================================================
elapsed:   1.61 | threads:    1 | thread time: 0.15
features:     1 | skipped:    0 | efficiency: 0.09
scenarios:    1 | passed:     0 | failed: 1
======================================================
>>> failed features:
js failed:
>>>>
01: read('classpath:org/company/page_objects/readData.json')
<<<<
org.graalvm.polyglot.PolyglotException: not found: org/company/page_objects/readData.json       
- com.intuit.karate.resource.ResourceUtils.getResource(ResourceUtils.java:120)
- com.intuit.karate.core.ScenarioFileReader.toResource(ScenarioFileReader.java:122)
- com.intuit.karate.core.ScenarioFileReader.readFileAsStream(ScenarioFileReader.java:99)        
- com.intuit.karate.core.ScenarioFileReader.readFileAsString(ScenarioFileReader.java:95)        
- com.intuit.karate.core.ScenarioFileReader.readFile(ScenarioFileReader.java:53)
- com.intuit.karate.core.ScenarioEngine.lambda$new$0(ScenarioEngine.java:124)
- <js>.:program(Unnamed:1)

src/test/java/org/company/order.feature:9
<<<

HTML report: (paste into browser to view) | Karate version: 1.1.0
file:///C:/Test/karate-maven-gradle-master/target/karate-reports/karate-summary.html
===================================================================

com.intuit.karate.KarateException: there are test failures !
        at ...(.)
The terminal process "cmd.exe /d /c java -cp karate.jar;karate-robot.jar com.intuit.karate.Main "c:\Test\karate-maven-gradle-master\src\test\java\org\company\order.feature:8"" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
`

**Comment by techshashank80** [comment]
How can send you the project? Zip project is ready.

**Comment by techshashank80** [comment]
Otherwise this is Order.feature file code
@tests=order
Feature: order

    Background:
       

    @test=order1
    Scenario: order 1
        * def locaters = read('classpath:org/company/page_objects/readData.json')
        * print 'order 1'

    @test=order2
    Scenario: order 2
        * print 'order 2'

    @test=order3
    Scenario: order 3
        Given path '/order'
        When method get
        Then status 200

    @test=order4
    Scenario: order 4
        Given path '/order'
        When method get
        Then status 201
    
    @test=order5
    Scenario Outline: order 5
        Given path '/order'
        When method get
        Then status <statusCode>

    Examples:
    | statusCode |
    | 200        |
    | 201        |

and added only one Json file under org.company.page_objects.
![image](https://user-images.githubusercontent.com/34492336/134258786-51186224-9e86-4d3f-8610-af5038b0681b.png)

**Comment by kirksl** [comment]
@techshashank80 i can't reproduce the problem.  does it work if you use maven instead of karate.jar?  i didn't add karate.jar and it runs with this command:
mvnw clean test -f "c:\git\karate-maven-gradle\pom.xml" -Dtest=KarateRunner "-Dkarate.options=c:\git\karate-maven-gradle\src\test\java\org\company\order.feature:8"

![image](https://user-images.githubusercontent.com/24948266/134448737-39f16762-489c-44a2-b650-29001016fa2d.png)

**Comment by techshashank80** [comment]
Thanks for investigating. It works fine with maven but when I click "Karate Run"/ Karate.Debug" from feature file, it does not work. Did you click "karate Run" from feature file?

**Comment by kirksl** [comment]
@techshashank80 yes both work.  here's a video of setting up debugging and running everything.
https://recordit.co/018kyWH0vD

**Comment by techshashank80** [comment]
@kirksl  Thank you, your video helped me to figure out the problem. If I have karate.jar and karate.robot.jar in the project folder and use standalone debug it does not work. so I removed these two and used maven it worked fine with Maven debug config.
The issue with if we add these jar names "java -cp karate.jar;karate-robot.jar;. com.intuit.karate.Main" name karate runner extension then it does not work for me.

**Comment by kirksl** [comment]
@techshashank80 happy to help.  you might want to follow up with the official [Karate project](https://github.com/intuit) and see if the "java -cp" command you are trying to run is supported.  also make sure you are using the correct version of karate.jar possibly?

one more link that might be useful.
https://github.com/intuit/karate/wiki/Debug-Server#karate-cli

feel free open a new bug here if there's still an issue plugin related...
