### ISSUE TITLE
'Karate: Run' codelens runs all gradle tests instead of just the selected feature/scenario

### ISSUE THREAD

**Issue by kelly-dealerware** [kirksl/karate-runner#122]
Clicking 'Karate: Run' inside a feature file should run only that feature or scenario, depending on what was clicked, but it runs ALL tests when used with Gradle, and then runs just the selected test again.  'Karate: Debug' however, works as expected.

Note: the '...' ellipses below are placeholders for brevity and security.

Karate Runner uses this command (note the 'test' command, which runs all Gradle tests) for 'Run':
```
./gradlew clean test -b "/.../build.gradle" karateExecute -DmainClass="com.intuit.karate.cli.Main" --args="/.../src/test/resources/api/login/login.feature"
```

Karate Runner uses this command for 'Debug':
```
./gradlew compileTestJava -b "/.../build.gradle" karateExecute --args="-d"
```

I think the command should be the same for both ("compileTestJava") except that the debugger should not be started when using 'Run'.
Run: `./gradlew compileTestJava -b "/.../build.gradle" karateExecute`
Debug: `./gradlew compileTestJava -b "/.../build.gradle" karateExecute --args="-d"`

Debug seems to not use the filename while run does, but it seems to work.

**Comment by kelly-dealerware** [comment]
@kirksl This is not project-specific.  It's the Runner code that is doing this.  The commands being run are incorrect for the KarateRunner gradle implementation when using the 'Karate: Run' codelens.  I can take a few minutes this afternoon and walk through the code and see where it's happening.  This is the 'karateExecute' task I use in every project:

```
tasks.register("karateExecute", JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    main = "com.intuit.karate.cli.Main"
}
```

**Comment by kirksl** [comment]
@kelly-dealerware this might be project configuration specific.  eg notice how in the sample project referenced above 'karate-maven-gradle' karateExecute is defined as follows https://github.com/kirksl/karate-maven-gradle/blob/master/build.gradle.kts#L151

it might not hurt just to try that project for a quick process of elimination check.  i have worked quite a bit with Karate and Peter to ensure the commands are defined correctly.

**Comment by kelly-dealerware** [comment]
@kirksl Alright, I'm not sure what it was, when I run yours it worked on both maven and gradle, then when I ran mine it worked correctly, without changing any code/config.  I wonder if it was a VSCode issue and running your project settled it down.

Anyway, closing this as it's not an issue anymore.  Thanks for the pointers!

**Comment by kirksl** [comment]
@kelly-dealerware happy to help.  let me know if it happens again!
