### ISSUE TITLE
color issues with new karate language addition

### ISSUE THREAD

**Issue by kirksl** [kirksl/karate-runner#13]
attached screenshot showing * configure json properties are not colorized.  attached test.feature file repro'ing the issue.

![image](https://user-images.githubusercontent.com/24948266/70560373-51598e00-1b3d-11ea-938d-c1c55c7e1034.png)

**Comment by kirksl** [comment]
[test.zip](https://github.com/kirksl/karate-runner/files/3946765/test.zip)

**Comment by kirksl** [comment]
![image (3)](https://user-images.githubusercontent.com/24948266/70573121-23cd0e80-1b56-11ea-9ab4-93a7edc18054.png)
![image (2)](https://user-images.githubusercontent.com/24948266/70573122-23cd0e80-1b56-11ea-8dc6-d2de6b2c533f.png)
![image (1)](https://user-images.githubusercontent.com/24948266/70573123-23cd0e80-1b56-11ea-83ff-0a7db8d018da.png)
![image](https://user-images.githubusercontent.com/24948266/70573124-2465a500-1b56-11ea-8520-ab8948e041f3.png)
![image (4)](https://user-images.githubusercontent.com/24948266/70573125-2465a500-1b56-11ea-924b-4314e645aa95.png)

**Comment by kirksl** [comment]
notating images from prior comment
- it would be nice if "print" was colorized in 1st image
- it would be nice if "call" was colorized in 2nd image
- first @tag is white, second @tag is red in 3rd image
- json properties not colorized when using call in 3rd image
- found "delete" word is colorized when used as part of a tests @tag in 4th image
- found ending quote and paren for "call read" is colorized as though its string data in 4th,5th images

**Comment by peterquiel** [comment]
Created https://github.com/kirksl/karate-runner/tree/bug/issue-13/color-issue-with-new-karate-language-addition to work on these issuses

**Comment by paaco** [comment]
@peterquiel The parameters of `select`, `click` or `input` actions appear as Javascript code, while they are in fact just strings (note the locators here are xpaths, not css selectors):

![image](https://user-images.githubusercontent.com/22741486/74945429-07700c80-53f8-11ea-92c3-ad3443208575.png)

Or even (notice how the "value" disappears in the green inline comment):

![image](https://user-images.githubusercontent.com/22741486/74946237-481c5580-53f9-11ea-8da2-766ae156dbff.png)

Somehow this similar example is not colored:
![image](https://user-images.githubusercontent.com/22741486/74945751-8e24e980-53f8-11ea-9f28-b237b7874926.png)

The same most likely applies for the other karate-core keywords, see here:
https://github.com/intuit/karate/tree/master/karate-core

**Comment by ptrthomas** [comment]
@paaco just hijacking the discussion for a moment, since I lurk here as well

do you think an improvement to the "wildcard locator" would be an enhancement

`* click('{input@type=submit}Bereken')`

and I thought this would be already an alternative for the last line above:

`* click('{^button}Sample')`

but yes if you want to "standardize" on XPath, what you have works I guess

**Comment by paaco** [comment]
@ptrthomas well I was merely pointing at additional strange syntax highlighting. Maybe it's just because of the at-sign.

Anyway, I like the fact that the "wildcard locator" is really short, but it's yet another way of specifying an element, next to css selector or xpath. Personally I would not extend it much further.

I use XPath (or css) because I can copy/paste that in a browser and see what it selects in the console with $x("//xpath"). That really helps in developing the test. I can't do that with the wildcard locator.

**Comment by kirksl** [comment]
syntax highlighting is a work in progress especially with the new UI syntax.  @peterquiel i've made some updates to the branch you have for this to solve prior issues and some of what @paaco is pointing out.  when ready i can update your branch with changes.

here are fixes for first level UI syntax calls.
![image](https://user-images.githubusercontent.com/24948266/74978599-cc62de80-53e1-11ea-9559-c63ea8967b27.png)

**Comment by kirksl** [comment]
@peterquiel @paaco i've released a new version of karate runner today.  all coloring issues with the exception of chained calls shown in the last image are fixed.  i'll leave this bug open to address that and we should be good to close this.

**Comment by paaco** [comment]
@kirksl thanx, this already looks some much better to my eyes

**Comment by KostasKgr** [comment]
Hello @kirksl , something that I noticed looking good on the intellij highlighting is the highlighting of variables in a scenario outline.

Intellij:
![image](https://user-images.githubusercontent.com/13213567/87707914-8cdec980-c7aa-11ea-8b7e-4ec34818d82d.png)

VS Code:
![image](https://user-images.githubusercontent.com/13213567/87707942-98ca8b80-c7aa-11ea-9ea4-b5d016ed60d9.png)

**Comment by kirksl** [comment]
thanks @KostasKgr agreed that looks nice.  sometimes user themes get in the way and try to set some of this stuff too.  eg image below coloring the angle bracket variable in the eval code but not in the table.  we'll see what we can do.
![image](https://user-images.githubusercontent.com/24948266/87730894-ec72b000-c77d-11ea-9daf-f24891b34b57.png)

**Comment by kirksl** [comment]
closing.  most issues have been resolved at this time.  please open new tickets for any remaining issues.
