### ISSUE TITLE
TypeError: Access to host class is not allowed or does not exist

### ISSUE THREAD

**Issue by abbringas** [kirksl/karate-runner#138]
Encountered this error below when using Karate runner VSCode extension but working fine when run as JUnit test.
org.graalvm.polyglot.PolyglotException: TypeError: Access to host class examples.users.Helper is not allowed or does not exist.

When run using Karate Runner:
![image](https://user-images.githubusercontent.com/69393091/161438173-b5f29b8e-2c13-43c7-8f86-c37b0ea0e5d0.png)

When run using JUnit/Karate test
![image](https://user-images.githubusercontent.com/69393091/161438155-a028f6c0-7225-4350-b47d-cb81a28bdcfb.png)

**Comment by kirksl** [comment]
@abbringas can you duplicate using this project?
https://github.com/kirksl/karate-maven-gradle

If not can you post a sample project

**Comment by abbringas** [comment]
Sorry for the late response. here's the sample project I used and shown from the screenshots. Let me know if you need anything else.

**Comment by abbringas** [comment]
@ki

> 

@kirksl hoping to have an update on this. Is it a bug?

**Comment by kirksl** [comment]
@abbringas Looks like you just need to update `Karate Runner > Karate Jar: Command Line Args` in VSCode Settings to point to include your `test-classes`.  See attached image where I updated that setting to `java -cp karate.jar;target/test-classes com.intuit.karate.Main`.  Note change the semicolon to a colon if you are Mac/Linux.

Happy as well to take a PR on the karate-runner project if you want to contribute and enable auto-detection of classpaths.  I can give you some pointers if interested.

![image](https://user-images.githubusercontent.com/24948266/163743513-b9f838ad-24ae-4c6f-a14c-8ac1f4ed88da.png)

**Comment by kirksl** [comment]
@abbringas Closing as this appears resolved.  Please open a new ticket if you have any further issues.  Thank you.

**Comment by AlekyaKowta** [comment]
I still have this issue. I have a Java class in another folder of the same project. I defined this in the feature file -   * def SasGenObject = Java.type('com.x.common.SASGen'). I keep getting the error: org.graalvm.polyglot.PolyglotException: TypeError: Access to host class com.x.common.SASGen is not allowed or does not exist. 
I've even added the include test-classes

**Comment by kirksl** [comment]
@AlekyaKowta can you duplicate using this project?
https://github.com/kirksl/karate-maven-gradle

If not can you post a sample project

**Comment by AlekyaKowta** [comment]
hi! I have realized it was because the module dependencies were not loaded properly. I had to right-click on my folder, open the module settings, and add dependencies from there. That solved it.
Thank you!
