### ISSUE TITLE
Is it possible to turn off the Karate syntax highlight?

### ISSUE THREAD

**Issue by ianrenauld** [kirksl/karate-runner#14]
I was very, very happy with this extension to run my Karate tests and I had found another extension to provide Syntax Highlight for my Karate Feature files.

Now with the latest release of this plugin, I really, really don't like the look of the Syntax Highlight that is now provided (it looks awful on my display theme - the images I see in Issue #13 look nice, but that's not my display theme). I can't switch to my previous one, because I lose the Karate *Runner* feature.

I strongly suggest to provide a way to turn off the new syntax highlight (or even better: split off the syntax highlight into another extension).

**Comment by kirksl** [comment]
@ianrenauld can you post some screenshots showing the bad experience.  another contributor to this project added this and i can discuss further to see if we can resolve.  on the interim i will look into adding a temporary workaround to disable it.

**Comment by ianrenauld** [comment]
I use the standard Monokai color theme and this is what I get. The red color everywhere is a bit much... 

<img width="754" alt="Karate Runner" src="https://user-images.githubusercontent.com/16843123/70760801-d8af2900-1d18-11ea-8148-70998fd1cc69.png">

Contrast this with the other extension, which is more soothing:

<img width="738" alt="Feature Syntax Highlight" src="https://user-images.githubusercontent.com/16843123/70760811-e5cc1800-1d18-11ea-869d-9d907c30767b.png">

Thanks for the workaround of using the previous version. Karate Runner is a MUST HAVE extension!

**Comment by kirksl** [comment]
@ianrenauld thanks for the screenshots.  i've forwarded everything on to the contributor.  also thank you for the feedback glad to hear we are making a difference!

**Comment by peterquiel** [comment]
Thanks for the feedback and Indeed, it looks awful. 

Explanation: I did not create a new theme, I just created a TextMate Grammar that defines Scopes for tokens. The `Given,When,Then,And,But,*` stuff is scoped as `keyword.language`. 
The theme tells vscode how to colorize the different scopes. 

So maybe, it's an attribute of Gherkin syntax, to have that many keywords. 

I will try to find "better scopes" that work with the Monokai Theme.

@ianrenauld: As a workaround: You can change the language mode back to `feature`. 
You should see  `Karate` in the lower left corner:
![image](https://user-images.githubusercontent.com/13017110/70780009-f619dc80-1d84-11ea-9197-ad7d2e79d899.png)

Click and change to `feature`. Codelense, folding and debugging should work as usual.

**Comment by kirksl** [comment]
closing as there are sufficient workarounds for now and our goal won't be to turn off highlighting, but to fix all issues in https://github.com/kirksl/karate-runner/issues/13
