### ISSUE TITLE
VS Code karate config js error while running scenario with java 1.8 and karate zip release version 1.2.0.RC1

### ISSUE THREAD

**Issue by smtripathi99** [kirksl/karate-runner#142]
I am getting following error while running a scenario file from VS Code 1.53.2 with Java 1.8 and karate version 1.2.0.RC1, Windows 10 64 bit:

 [main]  ERROR com.intuit.karate - src/demo/api/httpbin.feature:4   
* url baseUrl
js failed:
>>>>
01: baseUrl
<<<<
org.graalvm.polyglot.PolyglotException: ReferenceError: "baseUrl" is not defined
- <js>.:program(Unnamed:1)

src/demo/api/httpbin.feature:4

karate-config.js file:

function fn() {
   
        config.baseUrl = 'https://jsonplaceholder.typicode.com'
    }

    return config;
}
  
feature file:

Feature: simple requests

Background:
    * url baseUrl

Scenario: simple post
* url
* path 'anything'
* request { foo: 'bar' }
* method post
* status 200
* match response contains { json: { foo: 'bar' } }

**Comment by smtripathi99** [comment]
![image](https://user-images.githubusercontent.com/6882210/165167932-4d52c95b-7e65-4fa3-88a4-d34c3d3c1752.png)

**Comment by kirksl** [comment]
@smtripathi99 I see a couple of problems.

1. I don't see `var config = {}` set in karate-config.js.
2. You should remove `url` from line 7 in httpbin.feature.
3. karate-config shows an error the red number `1` in the treeview.  That is likely part of the problem.
4. Please see the screenshot attached below that works when I test this same scenario.

If you are still having trouble please upload a small project with the issue.

![image](https://user-images.githubusercontent.com/24948266/166289875-8392c111-220d-43fc-a287-f539f23c24d3.png)

**Comment by smtripathi99** [comment]
Thanks , how can I upload a project here?

**Comment by smtripathi99** [comment]
[https://github.com/smtripathi99/karatepoc](url)

**Comment by kirksl** [comment]
@smtripathi99 I looked at your project files from the github link.

It works for me when I add karate.jar to the root of your project.  Note you will still see an error because the baseUrl value in karate-config.js should be ```config.baseUrl = 'https://httpbin.org'```.  Once you change baseUrl it should succeed.  Please let me know if you are still having problems.

**Comment by kirksl** [comment]
@smtripathi99 great glad you got it working.  I will close this issue.  Also please consider opening a ticket with Karate Labs if this is a documentation issue.
