### ISSUE TITLE
Feature Request :- get Scenario tag name intellisense in calling feature

### ISSUE THREAD

**Issue by ajmera25** [kirksl/karate-runner#143]
I am having a feature called Feature1 and in this i am having a scenario called Scenario1 and Scenario2.

Scenario1 is having tag as @smoke

Now, From another feature i want to call only Scenario1 then the syntax is 
  * call read('classpath:common/Feature1.feature@smoke').
Here is it possible to have intellisense so that when i write @ then it give me all the tag present in Feature1.feature.

**Comment by kirksl** [comment]
@ajmera25 thank you for the feature request.  This should be possible we'll update intellisense logic to additionally show tags as selectable options and include this in our next release.
