### ISSUE TITLE
run single test doesn't work

### ISSUE THREAD

**Issue by tpetru** [kirksl/karate-runner#147]
Hello, I'm new with Karate, and I don't know where to post.

I have 2 features files, with different tests and I'm trying to **run a single test**, and **it's not working**. Do we have an issue, or I did something wrong, or maybe my configurations?

_(when I use **mvn test**, all tests are running)_

I tried to run only 1 test  in two ways:

1. with **CMD+R+1**, when a line with Scenario is focused and clicked
2. **click on Karate: Run**, after I unchecked _Clean Before Each Run_ and checked _Override Karate Runner_.

`
This is the terminal log:

[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.mycompany:KarateUdemy >----------------------
[INFO] Building KarateUdemy 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ KarateUdemy ---
11:37:11.971 [com.intuit.karate.cli.Main.main()] INFO  com.intuit.karate - Karate version: 1.2.0
11:37:12.082 [com.intuit.karate.cli.Main.main()] DEBUG com.intuit.karate.Suite - [config] classpath:karate-config.js
11:37:12.083 [com.intuit.karate.cli.Main.main()] INFO  com.intuit.karate.Suite - backed up existing 'target/karate-reports' dir to: target/karate-reports_1652690232083
Karate version: 1.2.0
======================================================
elapsed:   0.04 | threads:    1 | thread time: 0.00 
**features:     0** | skipped:    0 | efficiency: 0.00
**scenarios:    0** | passed:     0 | failed: 0
======================================================

HTML report: (paste into browser to view) | Karate version: 1.2.0
file:///.../karate-summary.html
===================================================================

Terminal will be reused by tasks, press any key to close it.
`

Apache Maven 3.8.5
Karate version: 1.2.0
Java version: 18.0.1.1
JUnit5

**Comment by kirksl** [comment]
@tpetru I tried on both Windows and Mac and keyboard shortcut, "Karate: Run" both work for me.  Can you try using our sample project here https://github.com/kirksl/karate-maven-gradle

Also keep in mind the cursor must be on the "Scenario" or within it when using the keyboard shortcut.

**Comment by kirksl** [comment]
@tpetru closing.  please open a new issue if this is still a problem.
