### ISSUE TITLE
Question: Do you have plans for support to Karate for NodeJS?

### ISSUE THREAD

**Issue by charlyautomatiza** [kirksl/karate-runner#148]
Related to the recent version of [karate-npm](https://github.com/karatelabs/karate-npm).
Do you have plans to add support to run on this new version?

**Comment by kirksl** [comment]
@charlyautomatiza yes we do.  @ptrthomas wondering if `karate.executable( )` will support fully qualified paths on Windows, Mac, Linux?  this is currently breaking the historical design of Karate Runner.

![image](https://user-images.githubusercontent.com/24948266/168710545-caf3e162-b7be-4fc8-a845-acc648ff4796.png)

**Comment by ptrthomas** [comment]
not sure I understand, if the path exists, it should have run the test.

contributions are welcome to both the npm and core

**Comment by kirksl** [comment]
@ptrthomas happy to look into this.  jbang doesn't seem to find my locally built karate binaries.  any ideas?
![image](https://user-images.githubusercontent.com/24948266/168880699-97a6042f-1b0f-4139-b868-45c7e618a7a4.png)

**Comment by ptrthomas** [comment]
@kirksl try clearing out your local maven repo. jbang depends on the metadata, so just removing a JAR or sub-folder won't do

**Comment by kirksl** [comment]
@ptrthomas tried the below and having the same issue.
- removed/confirmed removal of the entire local maven cache: `rd /q /s %userprofile%\.m2\repository`
- rebuilt karate 1.3.0.SNAPSHOT: `mvn clean install -P pre-release -pl -karate-robot -DskipTests`
- reran test from karate-npm with same dependency issue: `npm run test "c:\git\karate-npm\karate\httpbin.feature:3"`

**Comment by ptrthomas** [comment]
no idea. sorry

**Comment by kirksl** [comment]
@charlyautomatiza we have implemented support for JS, NPM, Yarn, etc in the karate runner plugin.  note that only Linux and Mac will work right now until the previously mentioned issue https://github.com/karatelabs/karate/issues/2016 is resolved.
