### ISSUE TITLE
Cannot use with VS Code Insider

### ISSUE THREAD

**Issue by khoinguyen** [kirksl/karate-runner#149]
I intend to use Karate with Karate Runner on VS Code Insider (the versions below) to test the GraphQL server.

My repo is not Java but javascript/typescript. 

After install, I create the feature file, and it works ok with the Karate Cli. My feature file in `<root>/test/karate`, run `karate test` in `<root>` give me the desire result

VS Code editor with Karate Runner display the feature file beautifully with CodeLens, but it not have any response when I click on `Karate: Run`

I tried to check on the `karateRunner.karateCli.overrideKarateRunner`, but no luck.

I go thru the document it said using `Preferences > Settings > Search for Karate Runner`, but there are no `Search for Karate Runner` in the Settings. Just `karateRunner.karateRunner.default` with `_SyncRunner`, I'm not sure what to change, or what to change to make it works.

Please advice

VS Code: 1.68.0-insider
Karate Version: 1.2.0
Karate Runner Version: 1.1.4

**Comment by kirksl** [comment]
@khoinguyen can you send the Karate Cli command you use that works and what Karate Runner is trying to run for a command in the VSCode IDE console.  also just a heads up we are waiting on a fix from Karate to enable support for Javascript/Typescript based projects.  https://github.com/karatelabs/karate/issues/2016

**Comment by kirksl** [comment]
@khoinguyen the way Codelens works is by searching for a file in the root of your project so that it can determine if it should use Maven, Gradle, etc.  if pom.xml is found use ```mvn command```, if build.gradle is found use ```gradle command```, etc.  there is currently no detection for javascript or npm specifically (so nothing happens as you see).  once Karate fixes the issue mentioned in my last post we will be releasing a new version of Karate Runner that detects package.json and if found use ```npm command``` likely ```npm run test```.

**Comment by khoinguyen** [comment]
hi @kirksl, as the link to the issue above, I far as I understand, it is a Windows-only issue, Mac/Linux users are ok with the current Karate version. Why can't we have it implemented for Karate Runner and let parts of the community continue their uses and report/contribute the functionality bugs/features/PR on it? Later, when it fixes, it can be quickly available for Windows users.

---
As you mentioned above regarding the `npm` command, I would like to request the settings for the command instead, as you may known, nowadays ppl not only use `npm`, but can be `yarn`, `pnpm` or even rush `@microsoft/rush` to manage their repo, the setting will be helpful in those cases

**Comment by kirksl** [comment]
@khoinguyen we were hoping to avoid special cases where we only ignore Windows.  if the fix from Karate takes awhile we will definitely release to support Linux/Mac and provide a warning that Windows is not yet supported.  thanks for your points on ```yarn```, ```pnpm```, etc.  time permitting we will definitely consider supporting more.  we are also happy to take a PR if you want to contribute and have time.

**Comment by khoinguyen** [comment]
Thank you @kirksl for your comments.

I will wait for sometime, in the mean time I can use karate client for my tests.

Will think about what I can contribute more for this project. Thank you for your contribution
