### ISSUE TITLE
Execute `Run Karate Test` via Keyboard Shortcut

### ISSUE THREAD

**Issue by peterquiel** [kirksl/karate-runner#15]
When I  add a keybinding to the `Run Karate Test` command and I press that key combination where the current cursor "selects" the scenario I want to run, I get the following error:

![image](https://user-images.githubusercontent.com/13017110/71247886-f3d1f800-2319-11ea-8420-44ab3195b2a8.png)

So, the expectation is, that I can run the Scenario I currently work on via a keyboard shortcut.

**Comment by kirksl** [comment]
@peterquiel fixed.  https://github.com/kirksl/karate-runner/commit/287b1fb2d04d57ddebf81bb499c33cde2175ed68
