### ISSUE TITLE
VsCodium support

### ISSUE THREAD

**Issue by jraduget** [kirksl/karate-runner#159]
Hi,
Any way to get karate-runner plugin for VsCodium platform ?
I have no clue on what is needed to port it.
Thanks for your support

**Comment by kirksl** [comment]
@jraduget Can you try the following steps and let me know if they work for you?
1. Goto https://marketplace.visualstudio.com/items?itemName=kirkslota.karate-runner
2. Click the "Download Extension" link on the right.  (This will download the extension/VSIX file)
3. Open VSCodium -> Click Extensions -> Click 3 Dots at top of Extensions -> Click "Install from VSIX"
4. Find VSIX downloaded in step 2 to install into VSCodium.

**Comment by jraduget** [comment]
Great, works fine. Thanks
