### ISSUE TITLE
Karatelabs VSCode extension

### ISSUE THREAD

**Issue by bischoffdev** [kirksl/karate-runner#161]
Hello, I just learned that there is a Karatelabs VSCode extension now as well. Is this something separate to this one? Because it seems like a lot of the features that yours has for free they now offer as paid functionality.

**Comment by kirksl** [comment]
Hello.  Yes there are indeed two extensions.  This one (Karate Runner) which we started about 3 years ago that works with VSCode, VSCodium for free.  And recently Karatelabs started one for the Intellij Enterprise community.  Happy to add features to Karate Runner on request just let us know!

**Comment by bischoffdev** [comment]
I don't mean the one from KarateLabs for IntelliJ, I mean the one they started just days ago for VSCode.
https://www.karatelabs.io/visual-studio-code

**Comment by kirksl** [comment]
Apologies for the confusion.  Yes that is an enterprise spin off as Karate commercializes their product.  Definitely something separate.

**Comment by bischoffdev** [comment]
Thanks, all good 👍
