### ISSUE TITLE
Add experimental inline autocompletion for Karate language in editor and toggle to turn on/off

### ISSUE THREAD

**Issue by kirksl** [kirksl/karate-runner#162]

**Comment by kirksl** [comment]
https://github.com/kirksl/karate-runner/pull/165/commits/53147d315989bfb19b343aecd7112076f180d35e

**Comment by ianrenauld** [comment]
How are we supposed to indent on a new line when this is turned on?

The autocompletion suggests something on the blank line and if I press Tab it accepts the suggestion, but I just want to indent the line before I start typing something?

See line 10 here: I just want to indent to start writing my Karate code, but the autocomplete will now insert an unindented "Scenario" which is not what I want.  I don't think using the Tab key is the best idea for the autocompletion...

![How do I insert a tab](https://user-images.githubusercontent.com/16843123/216426378-848b44dd-3ea0-479f-abb6-40f90f330313.png)

**Comment by kirksl** [comment]
@ianrenauld Thank you for your feedback.  This feature is highly experimental and only in it's infancy.  You can definitely turn this off for now until we get time to work on this.  See screenshot.  Happy to accept your pull request if you have time to contribute too.

![image](https://user-images.githubusercontent.com/24948266/216466578-d022e918-77b0-47aa-8840-57b5c6601d99.png)
