### ISSUE TITLE
maven cli command not correct

### ISSUE THREAD

**Issue by ptrthomas** [kirksl/karate-runner#17]
I tried to point the [karate-runner] to the `karate/karate-demo` module of the karate source code.

navigated to `src/test/java/demo/driver/demo-03.feature` and clicked on the [Run Karate Tests] codelens at the top

but it was running all the tests, with some difficulty I tried to screenshot the command the [karate-runner] was issuing, here it is

![image](https://user-images.githubusercontent.com/915480/72775209-845e6980-3c33-11ea-8cd1-2867051f507d.png)

so it is doing a `mvn test` where I would have expected a `mvn exec:java`

I manually entered this command and it worked the way I wanted:

`mvn exec:java -Dexec.mainClass=com.intuit.karate.cli.Main -Dexec.args=src/test/java/driver/demo/demo-03.feature -Dexec.classpathScope=test`

I think this would be great to have working, I am surprised because I thought it used to work earlier, did something change ?

EDIT: plugin version 0.6.6

**Comment by kirksl** [comment]
@ptrthomas thanks for reporting.  this is a really delicate thing right as so many people are using the tool now without issues.  do you know why 'mvn test' is not working in your case?  can your pom.xml or similar be instrumented to make it work with 'mvn test'?  also curious what are the implications and is it possible to switch everyone over to just 'mvn exec:java'.  i'm assuming some people might be leveraging the 'test' phase in their pom.xml that could break.  if that is a troubling route, also wondering is there a way to detect when i would want to use 'mvn exec:java' vs 'mvn test'?

appreciate some insight on this to fast track fixing this.

**Comment by ptrthomas** [comment]
@kirksl here's my understanding, it has to be mvn test if using a runner. but when the intent is to use the cli it has to be exec:java. so I think it is ok to switch over those who have selected the option to "override karate runner" does that make sense ?

**Comment by kirksl** [comment]
@ptrthomas crystal clear.  removed 'test' if running with new karate cli for maven.  tested and appears fixed.  closing bug.  let me know if you still see an issue.  https://github.com/kirksl/karate-runner/commit/5c80ca638bb998577f6b8a9389cc191cc3a65bd0

**Comment by ptrthomas** [comment]
@kirksl works perfectly in 0.7.3 thanks for the quick fix !
