### ISSUE TITLE
Feature Suggestion: Enable user to switch karate.env easily 

### ISSUE THREAD

**Issue by cheanwei** [kirksl/karate-runner#170]
Currently user can change the karate.env variable in karate-config.js. But this require user to navigate to the file and update file.
In the context of testing, developers often need to switch between different environments frequently. To streamline this process, it would be convenient if the plugin could display the currently active environment and provide the option to switch to a different environment from the status bar.

**Comment by kirksl** [comment]
https://github.com/kirksl/karate-runner/commit/e0ec95d6785c85329155a1f57973e21d8db2f45f
