### ISSUE TITLE
Debugging mode seems not working

### ISSUE THREAD

**Issue by phipgn** [kirksl/karate-runner#171]
It had been working properly for me until yesterday:
It took a long time for waiting the debug server to start and aborted the session eventually.
<img width="249" alt="image" src="https://user-images.githubusercontent.com/22786385/219613853-60ad4a10-f8c2-46a2-b183-335045791df7.png">

But from the log it says debug server has started already:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/22786385/219614081-7e01f7d9-16dc-4630-b3e0-93371e9369bc.png">

What I did try from my end:
- I have restarted my machine a few times.
- I did a fresh installation for Vscode.
- I have already made sure that maven debug configuration has been set up properly in launch.json.
- Tests can still be running okay.

More information:
- I'm using a Macbook Pro 13 inch, Apple M1 with Ventura OS.
![image](https://user-images.githubusercontent.com/22786385/219999224-a0bfb311-4b2e-42be-9bbe-2dbb7f89bcd1.png)
- My launch.json file:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "karate",
      "name": "Karate (debug): Maven",
      "request": "launch",
      "feature": "${command:karateRunner.getDebugFile}",
      "karateOptions": "",
      "karateCli": "mvn test-compile -f \"${command:karateRunner.getDebugBuildFile}\" exec:java -Dtest=TestRunner -Dkarate.env=uat -Dexec.mainClass=com.intuit.karate.cli.Main -Dexec.args=\"-d ${command:karateRunner.getDebugPort}\" -Dexec.classpathScope=\"test\" ${config:karateRunner.karateRunner.commandLineArgs}"
    }
  ]
}
```

Please help to take a look. And anyone facing the same issue?

**Comment by kirksl** [comment]
@phipgn Can you delete and recreate your launch.json, then try again.  Karate is deprecating the method in which we connect with it and we had to redesign the launch.json as shown in this commit.

https://github.com/kirksl/karate-runner/commit/55221c231ffd0265c087d697ec292b8707fb0eae#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R626

**Comment by phipgn** [comment]
> @phipgn Can you delete and recreate your launch.json, then try again. Karate is deprecating the method in which we connect with it and we had to redesign the launch.json as shown in this commit.
> 
> [55221c2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R626](https://github.com/kirksl/karate-runner/commit/55221c231ffd0265c087d697ec292b8707fb0eae#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R626)

thanks @kirksl 
but still no luck
I added my launch.json file above
I tried to re-install vscode as well but it still doesn't work

**Comment by kirksl** [comment]
@phipgn can you reproduce this issue using our demo project?
https://github.com/kirksl/karate-maven-gradle

We tested this change using that project and debugging worked with Maven, Gradle and Karate.jar.

**Comment by phipgn** [comment]
> @phipgn can you reproduce this issue using our demo project? https://github.com/kirksl/karate-maven-gradle
> 
> We tested this change using that project and debugging worked with Maven, Gradle and Karate.jar.

Yes I can. However, I did some tests yesterday, debugging seemed to work fine on another machine (Windows OS). So I guess it's something wrong with my Mac. I added my machine and OS information in the first thread if anyone else is facing the same issue. Meanwhile, I will try to dig down more, I will ask another team mate to try debugging on his machine today and keep you updated. Thank you.

**Comment by sukmaragil** [comment]
Having the same issues when using debug mode, here my sample `launch.json`
```json
{
  "configurations": [
    {
      "type": "karate",
      "name": "Karate (debug): Maven",
      "request": "launch",
      "feature": "${command:karateRunner.getDebugFile}",
      "karateOptions": "",
      "karateCli": "mvn test-compile -f \"${command:karateRunner.getDebugBuildFile}\" exec:java -Dexec.mainClass=com.intuit.karate.cli.Main -Dexec.args=\"-d ${command:karateRunner.getDebugPort}\" -Dexec.classpathScope=\"test\" ${config:karateRunner.karateRunner.commandLineArgs}"
    }
  ]
}
```
Above launch json modified to use the default generated by vscode, and also not working. Here additional info of my machine
- MacBook Pro Intel core i7
- OS: Ventura.

Is it related to OS Ventura?

**Comment by phipgn** [comment]
> Having the same issues when using debug mode, here my sample `launch.json`
> 
> ```json
> {
>   "configurations": [
>     {
>       "type": "karate",
>       "name": "Karate (debug): Maven",
>       "request": "launch",
>       "feature": "${command:karateRunner.getDebugFile}",
>       "karateOptions": "",
>       "karateCli": "mvn test-compile -f \"${command:karateRunner.getDebugBuildFile}\" exec:java -Dexec.mainClass=com.intuit.karate.cli.Main -Dexec.args=\"-d ${command:karateRunner.getDebugPort}\" -Dexec.classpathScope=\"test\" ${config:karateRunner.karateRunner.commandLineArgs}"
>     }
>   ]
> }
> ```
> 
> Above launch json modified to use the default generated by vscode, and also not working. Also already tried to reinstall the plugin but not yet try to re-install the vscode. Here additional info of my machine :
> 
>     * MacBook Pro Intel core i7
> 
>     * OS: Ventura.
> 
> 
> Is it related to OS Ventura?

I have just asked a colleague to debug on his machine using Karate Runner (it's an Apple M1 13 Pro with Ventura OS as well). The weird thing is debugging works fine for him. I will have to dig out more. I added a screenshot of my Mac info in the first thread FYI.

**Comment by kirksl** [comment]
https://github.com/kirksl/karate-runner/commit/9775422eda822192ff58895f8d639410fede69c6

**Comment by kirksl** [comment]
@phipgn @sukmaragil we have found some versions of Mac that were not detecting when ports were free.  Please update Karate Runner to version 1.2.3 when available and let us know if you still have problems.

**Comment by phipgn** [comment]
@kirksl awesome, it works for me now
thank you so much for your quick resolving
![image](https://user-images.githubusercontent.com/22786385/220005016-e2a8ce42-9e66-445d-8e93-f8c375e36426.png)

**Comment by kirksl** [comment]
@phipgn 💯

**Comment by LuisLozanoInditex** [comment]
Hello.

I have some problem with Sonoma OS.

![image](https://github.com/kirksl/karate-runner/assets/94856011/ec5c0356-3807-4626-82aa-e098b947ecb2)

The debug stops here:
![image](https://github.com/kirksl/karate-runner/assets/94856011/bdb465e1-9b1d-43cf-9294-19418ccddc63)

The launch.json:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "karate",
            "name": "Karate (debug): Maven",
            "request": "launch",
            "feature": "${command:karateRunner.getDebugFile}",
            "karateOptions": "",
            "karateCli": "mvn test-compile -f \"${command:karateRunner.getDebugBuildFile}\" exec:java '-Dexec.mainClass=com.intuit.karate.cli.Main' '-Dexec.args=-d' '-Dexec.classpathScope=test' ${config:karateRunner.karateRunner.commandLineArgs}"
        }
    ]
}`


The port changes when I press debug.

**Comment by kirksl** [comment]
@LuisLozanoInditex Can you please try to reproduce your problem with our sample repository here
https://github.com/kirksl/karate-maven-gradle

If you are able to reproduce the issue please list all of your steps
