### ISSUE TITLE
Could not load source error whilst debugging external file

### ISSUE THREAD

**Issue by Mrsevic** [kirksl/karate-runner#175]
I've configured tests properly and when trying to step into the file or over it using this command I get an error.
E.g.:
* callonce read('file:test/Some.feature')  in the feature background phase returns an error "Could not load source 'test\Some.feature'".

Is there some limitation that I am potentially not aware of or I am missing on something?

Thank

**Comment by kirksl** [comment]
I would try without `file:` in the file path to `read()`
I tried your idea in the project for this repo and it works.
If you continue to have trouble it would really help if you submit a sample project with exact steps to reproduce the problem.
![image](https://github.com/kirksl/karate-runner/assets/24948266/533c56ec-c65c-44d2-9bd1-83014a607563)

**Comment by kirksl** [comment]
@Mrsevic Please open a new issue if you are still having trouble with this.  Thank you.
