### ISSUE TITLE
Karate v1.4.1 breaking changes

### ISSUE THREAD

**Issue by pooventhan** [kirksl/karate-runner#178]
Hello,

We've been on Karate Basic tier and got to admit that the [Karate Runner plugin](https://marketplace.visualstudio.com/items?itemName=kirkslota.karate-runner) been a game-changer in our daily automation test debugging tasks!

As we were going through the changelog for [Karate v1.4.1](https://github.com/karatelabs/karate/releases/tag/v1.4.1), we noticed the author had mentioned that "IDE debugging requires extra dependency" under breaking changes.

After bumping the Karate version from v1.4.0 → v1.4.1, and adding the `karate-debugserver` dependency in pom.xml, we had encountered the following error:
`error: IDE debug requires paid upgrade of the Karate Labs plugin / extension`

Appreciate if you could help to shed some lights on this. Thanks in advance.

**Comment by kirksl** [comment]
Hello @pooventhan 

I would open an issue with the Karate Labs as they control what requires a paid account.
https://github.com/karatelabs/karate/issues

**Comment by pooventhan** [comment]
Noted! Thank you @kirksl
