### ISSUE TITLE
run test without execution option

### ISSUE THREAD

**Issue by EdisonSL** [kirksl/karate-runner#179]
Hi, Thanks for you wonderful plugin,

My project is golang project, so not include any execution option,

But I will setup `karateRunner.karateJar.commandLineArgs`,

This option will include karate jar that put on user/bin folder,

for example `java -cp /Users/xxx/bin/karate-1.4.1.jar com.intuit.karate.Main`,

But I still need put karate.jar at my project root even this jar is useless,

Is any chance this plugin not check root jar exists if karateJar is setup?

**Comment by EdisonSL** [comment]
ok, thanks!

**Comment by kirksl** [comment]
@EdisonSL Can you help me reproduce this issue.  I tried the following steps and they worked for me.

Clone our demo repository https://github.com/kirksl/karate-maven-gradle
Copied karate.jar to /karate-maven-gradle/src/test/java/org
Created a feature file within /karate-maven-gradle/src/test/java/org/company
Set `Karate Runner > Karate Jar: Command Line Args` to `java -cp karate.jar com.intuit.karate.Main`
And ran the test which passed

Note that you do not have to put a path on karate.jar in the java -cp command as `Karate Runner` searches every folder backwards starting from where the feature file is until it finds it.

If you still have issues if you can provide me exact steps to reproduce it I would appreciate it.

**Comment by EdisonSL** [comment]
Hi, @kirksl ,
I want to skip copy step
`Copied karate.jar to /karate-maven-gradle/src/test/java/org`
because I don't want project include any jar file since this project is golang project
and people who want to run api test will use jbang to make karate run like bin file

**Comment by kirksl** [comment]
@EdisonSL Thanks I didn't realize you were using JBang.

Would you be able to provide me with a sample project or update ours https://github.com/kirksl/karate-maven-gradle with your JBang implementation so that we can test a fix for this.

**Comment by EdisonSL** [comment]
Thanks again for you help!
This is my sample project, you don't really need to start golang server,
Just demo my project struct.
https://github.com/SemonCat/ApiTestDemo

<img width="1331" alt="image" src="https://github.com/kirksl/karate-runner/assets/99721721/0ba8cdcc-3cde-440c-afe5-67860345d9ea">

**Comment by kirksl** [comment]
@EdisonSL Thank you.
We have created a fix and this will be available in our next release soon.

https://github.com/kirksl/karate-runner/commit/224dd5b2e8b85a02174b2bf0e66751057f2a2385
