### ISSUE TITLE
karate-config.js is not being executed when debugging with karate-runner 1.2.4

### ISSUE THREAD

**Issue by Mr-Possum** [kirksl/karate-runner#185]
https://github.com/kirksl/karate-maven-gradle
Karate Runner 1.2.4, Karate Jar 1.4.0

karate-config.js is not being executed (or vars defined in karate-config.js are not being set)
![capture](https://github.com/kirksl/karate-runner/assets/85253512/4b649e1d-fde3-4572-9172-65d2de1cd19d)

**Comment by kirksl** [comment]
I would follow up with Karate directly if you are still having issues.
But it looks like you need to put karate-config.js at the root of the project.
https://stackoverflow.com/questions/61913993/how-to-define-or-use-karate-config-js-in-standalone-jar
