### ISSUE TITLE
Debugging doesn't work with Karate version 1.4.1

### ISSUE THREAD

**Issue by phipgn** [kirksl/karate-runner#190]
Just want to confirm. So I upgraded Karate version to 1.4.1 (it was 1.4.0 previously).

I noticed that it complains about missing karate-debugserver dependency.
![image](https://github.com/kirksl/karate-runner/assets/22786385/610c1c46-6710-432f-b477-ddf7c9e9f01e)

But if I add the dependency, now it requires a paid subscription
<img width="631" alt="image" src="https://github.com/kirksl/karate-runner/assets/22786385/265d0be3-1e8b-412e-ba85-48507238daee">

Is anyone facing the same issue?
Debugging works perfectly fine if I go back to 1.4.0
I'm using a Macbook Pro Apple M1

**Comment by kirksl** [comment]
@phipgn I would advise opening a ticket with Karate Labs https://github.com/karatelabs/karate/issues as they control what features are paid or free.  Karate Runner and older versions of Karate should continue to remain free.
