### ISSUE TITLE
Has Debug Support Been Removed for Gradle?

### ISSUE THREAD

**Issue by adrian-85** [kirksl/karate-runner#191]
I'm attempting to port a Maven project over to Gradle, using a Kotlin build file.  The runner is working fine except for debugging:

```
Executing task: gradle compileTestJava -b "/Users/username/workspace/karate-api-demo/build.gradle.kts" karateExecute -DmainClass=com.intuit.karate.cli.Main --args="-d 49152"  


> Task :karateExecute FAILED
14:20:39.307 [main] INFO  com.intuit.karate - Karate version: 1.4.1
error: IDE debug requires paid upgrade of the Karate Labs plugin / extension
```

Now in Maven debugging still works fine, and as this has been a feature of the free runner for some time, I would expect that to continue.  So the message I'm seeing is confusing.

**Comment by kirksl** [comment]
@adrian-85 Please see this ticket.  Unfortunately there is nothing we can do from our end when using newer versions of Karate which Karate Runner relies on.

https://github.com/kirksl/karate-runner/issues/190

**Comment by adrian-85** [comment]
@kirksl What I found strange is I don't need that dependency for 1.4.1 Maven, and Runner debugs just fine.  It's not consistent.

**Comment by adrian-85** [comment]
Opened a ticket with Karate, will see what they say:
https://github.com/karatelabs/karate/issues/2476

**Comment by kirksl** [comment]
@adrian-85 While that gets sorted out you should be able to work around this issue by using an older version of Karate.

**Comment by adrian-85** [comment]
Yep, checked into that, but due to the security patches, going with an older version is less ideal than just going back to Maven.
