### ISSUE TITLE
Classpath issue with standalone runner

### ISSUE THREAD

**Issue by paaco** [kirksl/karate-runner#2]
The command line to run karate.jar generated by the karate-runner 0.20 is:
`java -jar karate.jar <extra-arguments> file.feature`

When using -jar, the classpath is implicitly set to just that jar file. This makes it impossible to use Java-interop from other jar or class files, or even use the karate.read() command.
Using -cp … in `<extra-arguments>` does not work, because it is overwritten by the -jar option.

A better approach could be to create the command line as follows:
`java -cp 'karate.jar;.' com.intuit.karate.Main <extra-arguments> file.feature`

This not only adds the karate.jar but also the directory where karate.jar is to the classpath, so it at least will pick up karate-config.js from there and allow read('classpath:karate-envs.json').

Note that you need ; semi-colon on Windows, but : colon on Linux.

**Comment by kirksl** [comment]
@paaco thank you for letting us know about this issue.  Can you provide a sample project that should work with your "java -cp" command.  I've started to look into this but when I call "java -cp karate.jar:com.intuit.karate.Main file.feature" I get an error saying "Could not find or load main class test.feature".

**Comment by ptrthomas** [comment]
@kirksl see if the info here helps: https://stackoverflow.com/a/56458094/143475

**Comment by kirksl** [comment]
@ptrthomas thanks for the link.  I just realized there is a space not a ":" or ";" after both jar files.  I can successfully run the following "java -cp karate.jar com.intuit.karate.Main file.feature".  Maybe ":" and ";" are only for delimiting multiple jar files?

**Comment by ptrthomas** [comment]
@kirksl yep, that's right

**Comment by kirksl** [comment]
@paaco @ptrthomas fixed.  entire command line can be set by user now.
https://github.com/kirksl/karate-runner/commit/680dd266ef6c995266ecc590e78cbbb29b5248b5

**Comment by paaco** [comment]
@kirksl Thanks!

You are right, using ":" in the class path separates different jar files on Linux. On Windows, Java expects a ";" instead. And in Windows Power Shell you need to escape the ; inside the classpath with single quotes compared to cmd.exe. All very confusing and unfortunate. At least now I can develop the test on my Windows workstation and run it in the Docker based Gitlab CI environment.
