### ISSUE TITLE
Can't run tests using new Karate CLI in VS Code

### ISSUE THREAD

**Issue by clmcdonald** [kirksl/karate-runner#23]
Previously, I have been using IntelliJ to run my Karate tests, which is working fine on version 0.9.4. However, I want to get the syntax highlighting and debug features in 0.9.5 using VS Code, but I am not able to configure the "Run Karate Test" button to work properly. I checked the box to use the new Karate CLI in my Settings. When I run the test, I get a warning that it cannot find my karate-config.js: `WARN com.intuit.karate - skipping bootstrap configuration: could not find or read file: classpath:karate-config.js`. So it seems like it is starting my classpath at a different level than IntelliJ does. Is there a way to set the folder where the base classpath should be?

Karate Version 0.9.5
Karate Runner Version 0.7.8
VS Code Version 1.42.1

**Comment by kirksl** [comment]
@clmcdonald do you happen to have an example project demonstrating the problem.  that might be the fastest way to solve this.  alternatively we can try to run through the paces of Q/A.  some things i'm wondering are what your project structure/file layout looks like, are you able to run karate tests manually from the command line (if so how does that command differ from the one the Karate Runner extension is executing in the console), last question does Karate Runner work in VSCode if you turn off running with the Karate CLI.

**Comment by clmcdonald** [comment]
@kirksl I have created a test repo that has the same structure as our projects. I am able to get the test to run fine in IntelliJ, but I cannot get it to run in VS Code. https://github.com/clmcdonald/KarateVSCodeTest

**Comment by kirksl** [comment]
@clmcdonald thanks for the project.  you mentioned you are able to run tests manually on the command line.  can you tell me what that command is.  i'd like to run it to ensure i have a good baseline and the project runs successfully on my end.

**Comment by clmcdonald** [comment]
@kirksl It won't work inside that test project because the Java code is not in place, but the way we do it now is just with `mvn test`. But I think that is using the old runner, not the new Karate CLI. I don't know how to run them from the command line using the Karate CLI

**Comment by kirksl** [comment]
@clmcdonald here's an example of running with the karate cli.  this comes from the karate demo project.  you should be able to update the paths to the pom.xml and the test and it should run... mvn clean compile -f "c:\projects\karate\karate-demo\pom.xml" exec:java -Dexec.mainClass="com.intuit.karate.cli.Main" -Dexec.args="c:\projects\karate\karate-demo\src\test\java\driver\demo\demo-03.feature" -Dexec.classpathScope="test"

**Comment by ptrthomas** [comment]
@clmcdonald are you on Windows by any chance ? I suspect this may be a windows-only issue - which I am looking into as well

**Comment by ptrthomas** [comment]
okay I think the VS Code terminal defaulting to "powershell" is the culprit. I think this is easy to fix and you need to change the terminal that VS Code uses, this can be done by going to `File > Preferences > Settings` and setting the terminal this this:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/915480/75844450-11ccd600-5dfc-11ea-972e-e4fd700813dd.png">

**Comment by clmcdonald** [comment]
@ptrthomas I must have a different issue because I use a Mac. I use the zsh shell.

**Comment by ptrthomas** [comment]
@clmcdonald never mind I think I found the issue. the VS Code plugin issues `mvn clean compile`

instead it should be `mvn test-compile` because only THEN would the files in `src/test/java` get copied over to the `classpath:`

so I think we have a fix, I will wait for @kirksl  to confirm, also do you think we should allow the `mvn` command to be configurable - I see a `clean before each run` option, but it does not seem to work :|

@clmcdonald as a workaround for now

**Comment by ptrthomas** [comment]
@clmcdonald edited comment above, and it should all work once you have done an intial `mvn clean test-compile` from a separate terminal of course

**Comment by clmcdonald** [comment]
That worked! Thank you

**Comment by kirksl** [comment]
@clmcdonald i've changed maven to execute "test-compile" instead of "compile" in the karate runner and published a new version that should be available to VSCode now.  please let me know if this does not resolve your issue.  https://github.com/kirksl/karate-runner/pull/24/commits/5f6329046d338fc27ef12b3c8c4c83b122658ee6

**Comment by wasimfyrose** [comment]
I am still facing the same issue in VSC(windows) even though its running with "mvn clean test-compile "

**Comment by kirksl** [comment]
@wasimfyrose do you happen to have an example project demonstrating the problem. that will be the fastest way to solve this as I can't reproduce the problem.
