### ISSUE TITLE
Change default key binding for "Run All Tests"

### ISSUE THREAD

**Issue by ianrenauld** [kirksl/karate-runner#29]
On a Mac, at least, the default key binding for "Run All Tests" is set to command-A. This seems a very dubious choice, as this is also the default binding for "Select All" and now, I simply cannot do a "select all" in my project, it's running all the Karate tests instead.

Even in a blank file in the project I can't "select all", because it tries to run all the Karate tests (there are none, it's a text file that hasn't been saved yet, but Visual Studio Code assumes it will be a Karate .feature file). I get the error message: "Cannot read property 'karateOptions' of undefined" at the bottom of the screen.

I will remove that key binding now that I found the issue, but again, it seems like a very bad idea to use an existing, well known key binding and override its functionality.

**Comment by kirksl** [comment]
@ianrenauld thanks so much for bringing this to our attention

we originally consulted the keymapping pdfs provided by microsoft
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf

and did not see a conflict.  these are clearly out of date and our apologies.

we'd like to keep shortcuts as intuitive as possible.  if you have a suggestion please let us know while we solve this.

**Comment by kirksl** [comment]
@ianrenauld 0.8.2 released with updated keybindings.  please let us know if there is still a conflict.
