### ISSUE TITLE
Having Terminal>External Windows Exec set to cmd.exe doesn't guarantee it isn't executed in powershell

### ISSUE THREAD

**Issue by Techmaster21** [kirksl/karate-runner#35]
Even though my _Terminal>External Windows Exec_ is set to _C:\Windows\System32\cmd.exe_, it still appears to run in powershell, as running individual karate tests via the extension doesn't work. The same command fails in powershell for the same reason, while it works fine in cmd.exe.

**Comment by kirksl** [comment]
@Techmaster21 hello.  can you try clicking 'Select Default Shell' in this image and set it to cmd.exe.  seems vscode has changed how you choose the default terminal.
![image](https://user-images.githubusercontent.com/24948266/78917358-9fc35e80-7a43-11ea-87e5-78464c861cdc.png)

**Comment by Techmaster21** [comment]
Yes, that worked, thanks! I created a pull request to update the documentation for changing default shell.
