### ISSUE TITLE
Debug should use the same CLI args defined and be consistent with Run

### ISSUE THREAD

**Issue by ptrthomas** [kirksl/karate-runner#38]
I am using the following CLI, a custom classpath:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/915480/80126611-f5a21580-85b0-11ea-94a2-837a72f14ae3.png">

When I `Run` all is good:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/915480/80126838-25511d80-85b1-11ea-85cb-8aedf6c0ee56.png">

But not for Debug: 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/915480/80126897-369a2a00-85b1-11ea-9143-ba93502fe52d.png">

This is actually quite important, the use-case is for desktop automation, BTW there are some draft instructions here, would be good if you can verify they look ok for Windows, single-quotes and all: https://github.com/intuit/karate/wiki/ZIP-Release#karate-robot

**Comment by kirksl** [comment]
@ptrthomas can you confirm that any command you set here
![image](https://user-images.githubusercontent.com/24948266/80557223-0ffe3980-898b-11ea-979e-6535d2a74e30.png)

will work by always suffixing it with -d switch.

if true this might be a simple fix as i can fetch it's value and add the switch.

**Comment by ptrthomas** [comment]
@kirksl yes just suffixing with `-d` should be fine

**Comment by kirksl** [comment]
@ptrthomas fixed.  delete your .vscode directory at the root of the project to setup  your debug configuration again.  https://github.com/kirksl/karate-runner/commit/326ae9d4d816d991d0467fd6ccc23dcfbd4d20ed

**Comment by ptrthomas** [comment]
@kirksl great ! works fine 👍
