### ISSUE TITLE
Cannot run karate-runner when doing Remote Development using SSH

### ISSUE THREAD

**Issue by ianrenauld** [kirksl/karate-runner#4]
This is very weird and I'm not convinced it is really an issue with the karate-runner, but for me it works flawlessly when working on local, but when I use a remote workspace using SSH in Visual Studio Code, karate-runner always fails because it uses a weird JAVA_HOME that I never defined:

```
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/java/latest/bin/java
The terminal process terminated with exit code: 1
```

Everything else seems to be working correctly. The maven plugin works, if I run the exact same command that the karate-runner uses in a terminal, it also works. It only fails when I click on "Run Karate Tests" and it only fails when working remotely.

Like I said, I doubt somewhat that this is a problem with karate-runner, but it's the only conclusion I can come up with. Maybe you have an idea of what could be causing it (maybe a dependency on another part of Visual Studio Code, maybe)?

Keep up the good work, I love this plug-in!

**Comment by kirksl** [comment]
@ianrenauld thanks for the feedback!  this is an interesting issue.  ultimately karate-runner is just constructing a command that it runs in a task.  the same command you'd run from a command line eg mvn, gradle, java -cp karate.jar, etc.  if you can provide me a repro that will help.  exact steps you took, how you setup your environment.  also if you have a command that does work on the command line to run your karate tests please let me know.  quite possibly we need to detect this type of environment and call the tests different.

**Comment by ianrenauld** [comment]
Well, in trying to describe all the steps to reproduce, I found out that my problem was fixed!

If anyone has similar troubles in the future, I think the key was to set the following in the settings.json (you can set those in the settings UI) for the remote and to **restart** Visual Studio Code (even though I'm pretty sure I had done all this when I did the bug report, but I guess I misremembered...):

```
{
  "java.home": "[proper path to JAVA_HOME]",
  "maven.terminal.useJavaHome": true
}
```
