### ISSUE TITLE
Support a new debugPreStep configuration parameter in launch config

### ISSUE THREAD

**Issue by ptrthomas** [kirksl/karate-runner#42]
On the Karate debug-server side, I've added support for a pre-step hook. This is explained here:

https://github.com/intuit/karate/wiki/ZIP-Release#pre-step-hook

In fact it works without any change needed on the VS Code plugin side. I think the only change needed is to declare it, else you get the warning squiggle as seen below:

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/915480/80859061-73ce7e00-8c7b-11ea-8e35-68ea2e71b195.png">

By the way I implemented the "Copy Value" feature as explained here: https://github.com/microsoft/vscode/issues/27950#issuecomment-613281366
<img width="716" alt="image" src="https://user-images.githubusercontent.com/915480/80859086-9fe9ff00-8c7b-11ea-841f-3a7c0e2574a9.png">

just mentioning in case this is something you'd like to add to the karate-runner documentation as well.

testing both the above should be simple, just build the `karate.jar` as per the developer guide: https://github.com/intuit/karate/wiki/Developer-Guide#build-standalone-jar-and-zip

**Comment by kirksl** [comment]
@ptrthomas nice additions.  ill try to get to this soon.  will Karate just ignore debugPreStep in the debug config if using a version of Karate that doesn't support it yet?  also can I document this will be in 0.9.6?

**Comment by ptrthomas** [comment]
- yes it will be gracefully ignored
- yes should be in 0.9.6 for sure and planning 0.9.6.RC3 in a couple of days

**Comment by kirksl** [comment]
now supported in debug configurations.  i left it out of the snippets though so a user would have to explicitly specify it by typing it in.  let me know if you think that is ok.  also didn't document anything about usage of the debugger.  there's so much to the debugger that i hoped users would goto the VSCode documentation the debuggers features to understand how to use it and all of it's features.  https://github.com/kirksl/karate-runner/commit/36ba80d791e73f986fbca2ca948d9476c94ad593

**Comment by ptrthomas** [comment]
@kirksl I think you have a canned snippet for the `debugPreStep` can you please change the comma to a `+`, this is because I decided to change the API slightly, apologies

<img width="474" alt="image" src="https://user-images.githubusercontent.com/915480/82526880-b84e8a80-9b52-11ea-8a04-2d9cd1df1884.png">

since I'm here can I ask - have you documented the need to switch the terminal from "PowerShell" to `cmd.exe` anyplace that I can point users to ? I'm finding this is a must-do when using the Karate Runner on Windows.

**Comment by ptrthomas** [comment]
I'm going to paste some images here so that I can refer to them in wikis :)

<img width="989" alt="image" src="https://user-images.githubusercontent.com/915480/82527066-19765e00-9b53-11ea-8b47-7e5a12f8fced.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/915480/82527097-3743c300-9b53-11ea-9ace-8802e3d077a1.png">

**Comment by kirksl** [comment]
@ptrthomas no worries.  i'll reopen to reshape that canned code snippet.  regarding switching to cmd.exe yes it's at the bottom of the readme also reflected in the VSCode market place here --> 
![image](https://user-images.githubusercontent.com/24948266/82576691-d4e0c780-9b3e-11ea-8730-7b85804f8679.png)

**Comment by ptrthomas** [comment]
@kirksl thanks ! also one more minor change, omit the `robot.` it can just be:

`input(Key.ALT + Key.TAB)`

**Comment by kirksl** [comment]
fixed.  https://github.com/kirksl/karate-runner/commit/5b251049a9090d103e770082bf4bc1cd4b53d81d
