### ISSUE TITLE
How to use jvm arguments while running karate tests

### ISSUE THREAD

**Issue by kevinprotoss** [kirksl/karate-runner#46]
Hello,

sorry for creating a question issue. However, I had tried several possiblities, such as `karateRunner.karateCli.commandLineArgs` or `karateRunner.karateJar.commandLineArgs`, neither works. 
How could I define my own jvm arguments for running karate tests. For example, if I click the `Karate:Run` button in the feature file. I hope to add more arguments in the mvn command, e.g., `–Dkarate.env=`, `-Djavax.net.ssl.keyStore=` and so on.

I can not find any documentation about that either. Could some one here help me. 

Best regards and great thanks.
Kevin

**Comment by kirksl** [comment]
hello.  we have future plans to enable better control of the command line for maven and gradle.  is setting your jvm args within your pom.xml an option for now?  https://stackoverflow.com/questions/39750348/how-to-add-vm-args-using-pom-xml-plugin

**Comment by kevinprotoss** [comment]
Hi kirksl,

I have tried `<argLine>-Dfile.encoding=UTF-8</argLine>` of `maven-surefire-plugin` plugin. It works, however the solution is not so convenient. That means, I need to sync and commit this changed pom always in the repo, what I don't want to. It could happen, that some environments varibles contain the local file path. I think such configurations should be kept local in the workspace, such as the environment tab in the eclipse. Maybe any Karate configuration  or launch configuration might be helpful.

I'm not sure if I can solve the problem while using Karate CLI standalone. I'll have a further try. 

Last but not least, this feature to control environments or jvm args is prefered for this extension. 

Best regards,

**Comment by kirksl** [comment]
thanks @kevinprotoss appreciate your high interest to get this fixed.  all your points are valid.  we'll try to fix this soon as it was already on our roadmap.

**Comment by kirksl** [comment]
fixed.  https://github.com/kirksl/karate-runner/commit/97c6a13acffccbe656e357b5ff584eb794dec45b
