### ISSUE TITLE
VSCode runner fails for running single scenario

### ISSUE THREAD

**Issue by MahatmaFatalError** [kirksl/karate-runner#59]
If I run a particular Scenario via the Run Codelens the mvn command fails for the default runner `_SyncRunner`:

```
mvn clean test -Dtest=_SyncRunner -Dkarate.options="/Users/git/api-tests/src/test/java/karate/health/health.feature:7" 
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project api-tests: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.)
```

My question: What is this `_SyncRunner` ?

If I run it with my junit5 test suite
```
class KarateTestSuite {
	@Karate.Test
	Karate testAll() {
		return Karate.run().relativeTo(this.getClass());
	}
}
```
surefire at least starts but fails as well:
```
mvn clean test -Dtest=KarateTestSuite -Dkarate.options="/Users/git/api-tests/src/test/java/karate/health/health.feature:7" 
...
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ api-tests ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running karate.KarateTestSuite
[main] INFO com.intuit.karate.RunnerOptions - found system property 'karate.options': /Users/git/api-tests/src/test/java/karate/health/health.feature:7
...
[ERROR]   KarateTestSuite.testAll no features or scenarios found: [/Users/git/api-tests/src/test/java/karate/health/health.feature:7]
```

An easy way to reproduce this on your side would be generate a sample project via [Maven quick-start](https://github.com/intuit/karate#quickstart) and then run an arbitrary scenario in VSCode with the ExamplesTest runner.

**Comment by kirksl** [comment]
Hello.  _SyncRunner is the default value you should change to point to the Java file running your Karate tests.  It appears your Java file might be called KarateTestSuite.java?  If true when you click on a Codelens to run a test there will be a pop-up asking for the name of your Java file also known as your Karate Runner file.  Simply change it from _SyncRunner to KarateTestSuite.  

Hope this helps.

**Comment by MahatmaFatalError** [comment]
@kirksl Yes, thats wath I thought, too. But I could not find documentation about the meaning of _SyncRunner. 

Nevertheless, this bug is more about the `no features or scenarios found` error when run with a real junit runner when which leads to the maven command stated above with the `-Dkarate.options=myfeature.feature:${line number of the selected scenario}`.

**Comment by kirksl** [comment]
@MahatmaFatalError great.  can you confirm that you can run your tests successfully when using KarateTestSuite instead of _SyncRunner.  or do you still get an error like 'no features or scenarios found'?

**Comment by MahatmaFatalError** [comment]
@kirksl yes, I still get the error 'no features or scenarios found'

**Comment by kirksl** [comment]
@MahatmaFatalError any chance you can post a sample project somewhere with the issue?  suspect this might not be related to this Karate Runner extension as it really just builds commands and fires them off.  happy to take a quick look.

**Comment by MahatmaFatalError** [comment]
As mentioned initially it is reproducable with the sample project from [Maven quick-start](https://github.com/intuit/karate#quickstart) that can be generated vie maven archetype. 
```
mvn archetype:generate \
-DarchetypeGroupId=com.intuit.karate \
-DarchetypeArtifactId=karate-archetype \
-DarchetypeVersion=0.9.5 \
-DgroupId=com.mycompany \
-DartifactId=myproject
```

**Comment by kirksl** [comment]
@MahatmaFatalError seeing lots of issues using that quick-start.  doesn't seem to work with classpath:linenumber which is what the KarateRunner extension uses.  i do know this in fact works as i have personal template projects in both maven and gradle that works.  just verified.

@ptrthomas can you recommend a template Karate project for Maven that works with Karate Runner?  i have plans to release my own on my Github at some point.

**Comment by ptrthomas** [comment]
don't have one. @MahatmaFatalError do consider contributing one please.

one suggestion is maybe use 0.9.6.RC4 - some CLI changes did go in

**Comment by kirksl** [comment]
@MahatmaFatalError let us know if you continue to have trouble with the current suggestions.  If needed I can post a sample template project that is setup for both maven and gradle.

**Comment by alirux** [comment]
I have the same issue as @MahatmaFatalError, with or without using the line number. For example, executing the whole feature:
<img width="546" alt="immagine" src="https://user-images.githubusercontent.com/31094105/88897923-57c38400-d24c-11ea-8af1-4c18b7450038.png">

I also upgraded Karate to 0.9.6.RC4 and used UsersRunner as the Karate Runner as suggested.
The karate project I used is generated by maven from the archetype without any modifications.

`
mvn clean test -f "/Users/git/test.karate/pom.xml" -Dtest=UsersRunner -Dkarate.options="/Users/git/test.karate/src/test/java/examples/users/users.feature"

[...]

[INFO] Running examples.users.UsersRunner
09:56:19.125 [main] INFO  com.intuit.karate.RunnerOptions - found system property 'karate.options': /Users/git/test.karate/src/test/java/examples/users/users.feature

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.521 s <<< FAILURE! - in examples.users.UsersRunner

[ERROR] testUsers  Time elapsed: 0.52 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: no features or scenarios found: [/Users/git/test.karate/src/test/java/examples/users/users.feature]

`

**Comment by MahatmaFatalError** [comment]
The error stays with karate 0.9.6.RC4.
I agree with @alirux, even running an entire feature `mvn clean test -Dtest=ExamplesTest -Dkarate.options="pathToProject/src/test/java/examples/users/users.feature"` fails as well. So it might not be related to the `classpath:linenumber` syntax.

```
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ myproject ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running examples.ExamplesTest
14:59:43.746 [main] INFO  com.intuit.karate.RunnerOptions - found system property 'karate.options': pathToProject/src/test/java/examples/users/users.feature
Warning: Nashorn engine is planned to be removed from a future JDK release
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.652 s <<< FAILURE! - in examples.ExamplesTest
[ERROR] testAll  Time elapsed: 0.65 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: no features or scenarios found: [pathToProject/src/test/java/examples/users/users.feature]
```

Since I don't have any project where the karate-runner VSCode plugin works, it would be great if you can provide yours.

**Comment by alirux** [comment]
@MahatmaFatalError, as a workaround, run directly the java class UsersRunner using "Run Test":

<img width="495" alt="immagine" src="https://user-images.githubusercontent.com/31094105/88943649-076c1680-d28c-11ea-8f80-f7f1794ffef7.png">

**Comment by kirksl** [comment]
@alirux @MahatmaFatalError please see the sample template project i just posted.
https://github.com/kirksl/karate-maven-gradle

cc: @ptrthomas

**Comment by alirux** [comment]
I have an error with maven:

mvn clean test -f "/Users/karate-maven-gradle/pom.xml" -Dtest=OrderRunner -Dkarate.options="/Users/karate-maven-gradle/src/test/java/org/company/order.feature"

Running org.company.OrderRunner
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:50)
	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:291)
	at ch.qos.logback.contrib.jackson.JacksonJsonFormatter.<init>(Unknown Source)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.379 sec <<< FAILURE! - in org.company.OrderRunner
testParallel(org.company.OrderRunner)  Time elapsed: 0.378 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge

It happens also with a simple mvn clean test

Let me know if I can help

**Comment by kirksl** [comment]
@alirux please try pull the project down again and try.  github has a dependency bot that made a recommendation for a version change in the pom.xml that broke the project.  i've reverted that change and it works again.

**Comment by kirksl** [comment]
closing ticket as this appears to be a project and/or build configuration issue unrelated to the karate plugin.  a karate template project proving this fact can be found at https://github.com/kirksl/karate-maven-gradle

**Comment by alirux** [comment]
Now the project works.
But is it possible that the problem with the archetype project could be the JUnit version?
Your project uses JUnit4 whereas the archetype uses JUnit5.
I'm new to Karate but if I'm not wrong, the karate.options variable with features and tags are used only with JUnit4.

**Comment by MahatmaFatalError** [comment]
> But is it possible that the problem with the archetype project could be the JUnit version?
> Your project uses JUnit4 whereas the archetype uses JUnit5.
> I'm new to Karate but if I'm not wrong, the karate.options variable with features and tags are used only with JUnit4.

@kirksl Thanks for providing the sample project. 
@alirux Indeed, your hint is correct. It works with Junit4. However, after I switched the project to Junit5 if fails with 
```
Junit5Runner.testAll no features or scenarios found: [/PathToProject/karate-maven-gradle/src/test/java/org/company/order.feature:12]
```

Please see this commit of my fork https://github.com/MahatmaFatalError/karate-maven-gradle/commit/d27fa9d67bc4a43086daee842ee6e1bb3f3b2668

**Comment by kirksl** [comment]
@alirux @MahatmaFatalError upgraded template to support Java 11 LTS and JUnit 5.  https://github.com/kirksl/karate-maven-gradle

**Comment by MahatmaFatalError** [comment]
Thanks for the fix. After briefly comparing both approaches it seems the main difference is the usage of `org.junit.jupiter.api.Test` annotation instead of `com.intuit.karate.junit5.Karate.Test` [annotation](https://github.com/intuit/karate#junit-5). Likely because of https://github.com/intuit/karate#junit-5-parallel-execution ?

As I do not want any parallelism this solution still seems strange to me.

**Comment by ptrthomas** [comment]
@MahatmaFatalError I don't find it strange. just use a thread count of 1. I'll happy to hear your suggestions on how this can be made less "strange"

**Comment by MahatmaFatalError** [comment]
@ptrthomas since there is no statement like "Limitations: `@Karate.Test` is not supported. Use xyz instead." in the documentation, it confuses users who are using this in itself valid annotation.

**Comment by ptrthomas** [comment]
@MahatmaFatalError sure, feel free to submit a PR for the documentation. right now I don't understand the issue fully, personally I don't consider it a priority so it is a case where I hope the community can pitch in, else it will be status quo
