### ISSUE TITLE
Support for build.gradle.kts

### ISSUE THREAD

**Issue by tblakers** [kirksl/karate-runner#60]
Kotlin Script is the future of Gradle, and it would be nice to support it. Looking through the code, it seems it could be as simple as allowing both "build.gradle" and "build.gradle.kts" as filenames?

**Comment by kirksl** [comment]
@tblakers we can absolutely look into supporting this.  can you help me understand if there would be any changes to the gradle command line.  if the command line is identical i can update this pretty quick.

**Comment by kirksl** [comment]
note to add kotlin alongside groovy snippets in readme.  @tblakers appreciate if you can check kotlin syntax.

// groovy
task karateExecute(type: JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    main = System.properties.getProperty('mainClass')
}

// kotlin
task("karateExecute", JavaExec::class) {
    classpath = sourceSets.test.runtimeClasspath
    main = System.properties.getProperty("mainClass")
}

**Comment by tblakers** [comment]
My gradle knowledge is a bit weak, but tasks are often registered as follows:

val karateTask = tasks.register<com.package.mytask>("karateExecute") {
  // setters go here
}

Would be happy to play around with an alpha build, or if its just a matter of adding another filename I can make the change myself and submit a PR

**Comment by kirksl** [comment]
feel free to pull down the project and submit a PR.  i think you'll just need to search for files referencing string "gradleBuildFile".  commands.ts and helper.ts will need to be updated to additionally spec something like "gradleKtsBuildFile" and then all code referencing "gradleBuildFile" will need to accommodate "gradleKtsBuildFile".

let me know if you're comfortable doing this.  i can look into it when free as well.

also feel free to use this template project to test your changes
https://github.com/kirksl/karate-maven-gradle

**Comment by kirksl** [comment]
@tblakers curious if you've had a chance to look at this.

**Comment by tblakers** [comment]
Sorry I haven't been working with Karate over the previous couple months, maybe I'll have a chance to look at this over next month, but no promises

**Comment by kirksl** [comment]
no worries.  thanks for the update.

**Comment by peterquiel** [comment]
Support will be added with:
#72

**Comment by kirksl** [comment]
@tblakers support for kotlin has been added to karate plugin 0.9.5.  please let us know if you have any further issues.
@peterquiel many thanks for the help with this.
https://github.com/kirksl/karate-runner/commit/764922069508c29d96e9f9bfa58b59a1b4ecbb93
