### ISSUE TITLE
In standalone mode, karate.jar must be at root of project

### ISSUE THREAD

**Issue by blaisn** [kirksl/karate-runner#61]
I am using Karate-Runner plugin in VSCode and it appears that no matter how I play with the settings, CLASSPATH or commnand nothing works unless karate.jar is at the root of the project. Moving it to /bin for example, code lens has no effect within the editor.
In the settings:
    "karateRunner.karateJar.commandLineArgs": "java -cp 'karate.jar;./bin' com.intuit.karate.Main",
Has no effect.
Do you have a way to point to another directory?

**Comment by kirksl** [comment]
@blaisn can you describe why you need karate.jar in a location other than the root of the project.  we try to keep build.gradle, pom.xml and karate.jar at the root of projects for many reasons.  for detection by Karate Runner to know which tool you are using and to create a boundary at the filesystem level to determine where each project is when you have multiple projects loaded in the IDE.

**Comment by blaisn** [comment]
It is a question of keeping the root of the project as clean as possible. In our node project, we have the standard kit of files:
package*.json
Dockerfile
.gitignore
.gitattribute
,eslintrc
...
And for those files, it is usual (and significant) to see them at the root.
But only for the karate suite, we have to add:
karate.jar  (kind of executable that could be hidden in/bin ou /lib or /jar)
karate-config.js (could be hidden in the /config dir)
karate-logback-config.xml (as well in the /config dir)
)

So it is not major issue but it would be cleaner I suppose.
Thanks.

**Comment by kirksl** [comment]
backlogging this for now.  the level of work to make this happen is high for little benefit.  i do see your point though and appreciate keeping things clean especially at the root.

**Comment by kirksl** [comment]
closing and leaving on our backlog.  we'll revisit if there is enough demand for it.

**Comment by ivangsa** [comment]
Hi

We made this work for us: with a maven project we use `mvn dependency:copy-dependencies` to download karate and all dependencies to target/dependency and then configure this setting:

`"karateRunner.karateJar.commandLineArgs": "java -Dkarate.env=local -cp \"target/classes;target/test-classes;src/test/resources;target/dependency/*\"  com.intuit.karate.cli.Main"`

In this way code lens "Karate Debug" works like a charm. "Karate Run" still tries to run with pom.xml and many times it's failing, depending on default vscode terminal on windows.

I find this "auto select runtime" functionality and configuration in general somehow confusing...

I think we should be able to "select" which runtime we want for "Run" and for "Debug" and then configuration options for each runtime, it would be simpler.
