### ISSUE TITLE
Improve the doc please

### ISSUE THREAD

**Issue by blaisn** [kirksl/karate-runner#63]
For users who use the plugin standalone (without Maven or Gradle), it is pretty hard to find how to setup launch.json to configure the debug. I finally found it after hours of try and errors, in one of the videos, Please put this handy in your documentation!
Here is what works for me:
        {
            "type": "karate",
            "name": "Karate (debug)",
            "request": "launch",
            "feature": "${command:karateRunner.getDebugFile}",
            "karateOptions": "",
            "karateCli": "java -jar karate.jar -o test/rapport/karate -d"
        },

**Comment by kirksl** [comment]
@blaisn can you describe what did not work with the default debug configuration settings.  it looks like you changed "karateCli" property to a hardcoded value for your specific use case and project setup.

**Comment by blaisn** [comment]
You are right, I added the "-o" option to redirect the report output to a custom report folder. But it's working as well with the suggested 
"karateCli": "java -jar karate.jar -d"

My point here is not that this config does not work, My point is that it should be given directly in the plugin page:
https://marketplace.visualstudio.com/items?itemName=kirkslota.karate-runner
Hence, it will avoid users to loose time finding that piece of info, mandatory to make debug works.
Thanks!

**Comment by kirksl** [comment]
we will make a future improvement to link to Karate documentation from our documentation.  i believe you could have benefited from this link https://github.com/intuit/karate/tree/master/karate-netty#standalone-jar

**Comment by kirksl** [comment]
closing.  this work is complete and will be included in our next release.
