### ISSUE TITLE
Publish to https://open-vsx.org to support VSCodium in the spirit of open source

### ISSUE THREAD

**Issue by sporkisfaster** [kirksl/karate-runner#64]
Currently the karate plugin does not appear in the plugins for [VSCodium](https://vscodium.com). The process to do so can be found here: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

**Comment by kirksl** [comment]
@sporkisfaster thanks for the request.  i'd like to get some upvotes before making this part of our deployment process.  for a couple reasons.  this is extra process we don't want to take on unless there is good demand for it.  on the interim the VSIX can easily be downloaded and side loaded.  alternatively my vote is to just repoint to the marketplace where everyone is currently publishing to for VSCode and avoiding creating/managing duplicate VSIX files and stores.

**Comment by kirksl** [comment]
closing and leaving on our backlog.  we'll revisit if there is enough demand for it.
