### ISSUE TITLE
Add intellisense, autocomplete, linting features

### ISSUE THREAD

**Issue by kirksl** [kirksl/karate-runner#65]
Prior assessment revealed high cost to execute this work item.
Main cost is implementation against Karate's rich syntax and maintaining it over time.
This should periodically be re-assessed to examine factors to facilitate taking this on (eg increase in contributors, decrease in language churn, etc)
Ideally it would be great to have this detail defined in the core Karate project via a language/syntax based file that it's parsing engine works against.  This would greatly simplify maintenance and assurance we are always in parity.

Implementation of these should handle aspects of intellisense/autocomplete
https://code.visualstudio.com/api/references/vscode-api#CompletionItemProvider%3CT%3E
https://code.visualstudio.com/api/references/vscode-api#DeclarationProvider

Implementation of these should handle aspects of linting(further investigation needed)
https://code.visualstudio.com/api/references/vscode-api#Diagnostic
https://code.visualstudio.com/api/references/vscode-api#CodeActionProvider

**Comment by ptrthomas** [comment]
for those interested in contributing to the core project see: https://github.com/intuit/karate/projects/3#card-22529505 - if we implement LSP support, it should work in VS Code (and even some other IDE-s)
