### ISSUE TITLE
Show debug variables as json (instead of strings)

### ISSUE THREAD

**Issue by ivangsa** [kirksl/karate-runner#68]
Hi, 

when debuging, on a breakpoint..

is it posible to show debug variables as _expandable_ json objects?

currently I can only see them a json string with makes it harder to debug...

Thanks

**Comment by kirksl** [comment]
@ptrthomas wondering if this is something controllable from the DAP implementation when IDE requests variable info for stack frame?

https://microsoft.github.io/debug-adapter-protocol/specification#Types_Variable

**Comment by ptrthomas** [comment]
I think so, and I think `supportsValueFormattingOptions` and `VariablePresentationHint` which we don't set today has to be switched on. I'm busy with that rewrite which will anyway impact the debug adapter so will get around to it eventually. but any analysis / trial in the meantime would help

**Comment by kirksl** [comment]
@ptrthomas great.  thanks for confirming.
@ivangsa closing and solutioning for this can be tracked at https://github.com/intuit/karate/issues/1281

**Comment by ptrthomas** [comment]
@ivangsa ok, so we need your help now. you can see commit above that tries to "guess" what the solution should be: https://github.com/intuit/karate/commit/43c8a903b36b386263322bdc854635a430d24dd3

didn't seem to work. but by the way, note that when you right click on a variable and say "copy value" to clipboard, you get it pretty-printed

<img width="372" alt="image" src="https://user-images.githubusercontent.com/915480/101235119-97631680-36eb-11eb-94c1-75a736bab7d3.png">

so when you say: `expandable json objects`. 
* what do you mean ? do you have an example
* if this is something that VS code supports, please help us find the code that can enable this
* maybe you can look at the source of other plugins that deal with JS to see how it can be done, e.g: https://github.com/Microsoft/vscode-debugadapter-node/issues/123

without this, we won't be able to address this. hope you can help !

**Comment by ivangsa** [comment]
ok, I will have a look into this because vscode supports this for other debugers, this is what I mean:

![image](https://user-images.githubusercontent.com/1246876/101243599-ac4aa480-3701-11eb-9e7e-e6ad53521f94.png)

as you can see all variables can be expanded, as an structured tree... they are not just text..
this is very common in every debugger I have used

**Comment by ptrthomas** [comment]
@ivangsa ok. btw if you use slack: https://twitter.com/KarateDSL/status/937271659785961477
