### ISSUE TITLE
Unable to install in VS2019.

### ISSUE THREAD

**Issue by sudheertreddy** [kirksl/karate-runner#7]
Can you please help me out. I am unable to install in VS2019. I am getting below error.

9/22/2019 8:34:20 AM - Microsoft VSIX Installer
9/22/2019 8:34:20 AM - -------------------------------------------
9/22/2019 8:34:20 AM - vsixinstaller.exe version:
9/22/2019 8:34:20 AM - 16.2.3073
9/22/2019 8:34:20 AM - -------------------------------------------
9/22/2019 8:34:20 AM - Command line parameters:
9/22/2019 8:34:20 AM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Desktop\kirkslota.karate-runner-0.4.1.vsix
9/22/2019 8:34:20 AM - -------------------------------------------
9/22/2019 8:34:20 AM - Microsoft VSIX Installer
9/22/2019 8:34:20 AM - -------------------------------------------
9/22/2019 8:34:21 AM - Initializing Install...
9/22/2019 8:34:22 AM - Extension Details...
9/22/2019 8:34:22 AM - 	Identifier         : karate-runner
9/22/2019 8:34:22 AM - 	Name               : Karate Runner
9/22/2019 8:34:22 AM - 	Author             : kirkslota
9/22/2019 8:34:22 AM - 	Version            : 0.4.1
9/22/2019 8:34:22 AM - 	Description        : Run/Debug Karate Tests and open Build Reports from Codelens and Activity Bar.
9/22/2019 8:34:22 AM - 	Locale             : en-US
9/22/2019 8:34:22 AM - 	MoreInfoURL        : 
9/22/2019 8:34:22 AM - 	InstalledByMSI     : False
9/22/2019 8:34:22 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
9/22/2019 8:34:22 AM - 
9/22/2019 8:34:22 AM - 	SignatureState     : Unsigned
9/22/2019 8:34:22 AM - 	Supported Products : 
9/22/2019 8:34:22 AM - 		Microsoft.VisualStudio.Code
9/22/2019 8:34:22 AM - 			Version : 
9/22/2019 8:34:22 AM - 
9/22/2019 8:34:22 AM - 	References         : 
9/22/2019 8:34:22 AM - Signature Details...
9/22/2019 8:34:22 AM - 	Extension is not signed.
9/22/2019 8:34:22 AM - 
9/22/2019 8:34:22 AM - Searching for applicable products...
9/22/2019 8:34:22 AM - Found installed product - Global Location
9/22/2019 8:34:22 AM - Found installed product - Visual Studio Enterprise 2019
9/22/2019 8:34:22 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by kirksl** [comment]
@sudheertreddy thank you for reporting this issue.  can you provide exact steps you took to reproduce this error.  please ensure to provide exact versions and details about your platform such as version of Windows, Linux or Mac.

**Comment by sudheertreddy** [comment]
Hey @kirksl, I was installing without having vscode in my machine. I thought it would install in visual studio. Now my issue is resolved. Able to install vscode and then karate-runner.

**Comment by kirksl** [comment]
@sudheertreddy great!  glad it works for you.  please let us know if you have any questions.
