### ISSUE TITLE
Ignored scenarios should not be displayed in the Tests View

### ISSUE THREAD

**Issue by sahilaug** [kirksl/karate-runner#85]

**Comment by kirksl** [comment]
@sahilaug is your preference to hide the files and directory structure too if everything is set to "@ignore" beneath it?  that will incur a high compute cost as every file will have to be opened and parsed for the entire project.  large projects could really suffer and the compute cost will occur every time a node is expanded as well as the tree has to redraw itself.

also just a note one way to elegantly handle this is to use a naming strategy for your feature files.  eg feature files with actual tests end with _tests.feature, ex: email_tests.feature

**Comment by sahilaug** [comment]
@kirksl I understand the edge case you mentioned, I feel the react virtualised list (which I believe the vscode treeview uses under the hood) should take care of the redrawing, that's a solved problem in the frontend world IMO. But yes, there will be a one-time compute cost in parsing the feature files, which I believe we are already doing because we have to parse scenarios inside a feature file and list them in the treeview, we probably need to add the capability of reading tags before adding those scenarios in the treeview.
Some context for wanting this enhancement:
In most of the projects, I work with treeview is rarely used, as mostly karate is being run by command line by SDETs. What but where I feel the need for this plugin shines is when folks (especially manual testers moving to automation) are trying to run these from the UI, there I see them trying to play the test in the treeview and then wondering why its not running, then they finally open the feature file and discover that its @ignored by karate.

**Comment by kirksl** [comment]
@sahilaug i've improved the experience.  the treeview will show "ignored" string next to any feature, scenario, scenario outline if annotated with "@ignore".  when ignored the "run" and "run all" icons/commands will be hidden in the treeview as well.  finally in settings you can choose to hide the ignored tests too.

note this was a quick fix and could be further improved to hide parent folders as well, but i chose to wait and think about this more as i'm already seeing an increase in computing required and lag in the treeview for bigger projects, and this occurs everytime you click refresh.

let me know what you think.
https://github.com/kirksl/karate-runner/pull/87/commits/e06332088ac6da32db893f1606a0ce030a0715cc

**Comment by sahilaug** [comment]
@kirksl Thanks for the quick fix. Tested it out, works as expected. It worked fine in a mid-sized project with around 500 scenarios (I checked the refresh button as well). 
`treeItem.description = 'ignored'` adds a nice touch which I believe achieves the original intention of giving feedback to the user. 
Removing it from the treeview altogether would certainly be a cherry on top. I usually have reusable karate features (which just make an API call, minimum assertions), which I reuse for API workflow tests as well. Hence all those reusable feature files are never to be called individually and can be a substantial count (~70 in my case).
Thanks for taking the time out for the quick fix nevertheless. This helps, Cheers.

**Comment by kirksl** [comment]
@sahilaug happy to help.  you can hide *.feature files and their tests from the tree.  see attached images.  i did not hide parent folders as it seems like compute cost is rising faster than i would like.  perhaps a better code design would solve that.
![hide from tree no](https://user-images.githubusercontent.com/24948266/120077774-e2d5fc00-c060-11eb-8c4d-6ba1371e347d.png)
![hide from tree yes](https://user-images.githubusercontent.com/24948266/120077775-e36e9280-c060-11eb-8f13-7ecfd8ce59a0.png)
