### ISSUE TITLE
Debug Server fails to start (timeout)

### ISSUE THREAD

**Issue by pantoniotti** [kirksl/karate-runner#86]
Hi there,
I am using the Karate Runner everyday and it's really a cool piece of software. Unfortunately I never got to make it to work in Debug mode. here is my launch.json file, and the error I get when I try to run the Debugger.
Karate 0.9.6 with Maven

`{
      "type": "karate",
      "name": "Karate (debug): Maven",
      "request": "launch",
      "feature": "${command:karateRunner.getDebugFile}",
      "karateOptions": "",
      "karateCli": "mvn test-compile -f \"${command:karateRunner.getDebugBuildFile}\" exec:java -Dexec.mainClass=com.intuit.karate.cli.Main -Dexec.args=\"-d\" -Dexec.classpathScope=\"test\" ${config:karateRunner.karateRunner.commandLineArgs}"
}`

And the error is attached

![Screen Shot 2021-05-25 at 10 27 17 AM](https://user-images.githubusercontent.com/1122532/119520396-418d3400-bd48-11eb-8771-5fc50be10cc8.png)

Thanks a lot for you time (and help)

**Comment by kirksl** [comment]
@pantoniotti hello.  i was able to successfully debug maven with karate 0.9.6 using a demo project we use to test the karate runner extension.  https://github.com/kirksl/karate-maven-gradle

i cloned that project
checked out the last version with 0.9.6 support here: git checkout a770a9361396a249456a3f2d5b59ff0a8fab9481
updated the karate-config.js to use 'stg' environment to avoid using mocks (maven with mocks for this project needs to be fixed)
started spring boot server: mvn clean spring-boot:run
opened: order.feature
set a breakpoint on 'order 3' test
clicked 'Karate: Debug' for 'order 3' test
and debugging as successful as shown in attached image
![Untitled](https://user-images.githubusercontent.com/24948266/119547599-291e1900-bd4a-11eb-87b1-60bafe629ed1.png)

if you still have trouble if you can list your repro steps and provide a way to reproduce the project such as a small project that will really help.

**Comment by pantoniotti** [comment]
Hi Kirk, It helps !!! and worked right away once I added all the springboot stuff in the pom.xml :wink:
Unless I am mistaken the karateRunner doc does not mention anything about a server being required to run for Debug to work … Maybe you could add as example a link to the project you just sent me ? :wink:
In any case, Thanks a lot!!
